### ISSUE TITLE
Faceit anticheat

### ISSUE THREAD

**Issue by adagi** [EngineOwningSoftware/pcileech-webradar#2]
Hey,
you wrote that this radar is safe for Faceit. Do you mean the Serverside-AC or the Faceit-client?
Thanks

**Comment by Skyfail** [comment]
The Radar is safe to use with FaceIt client, just make sure to read the Security considerations

**Comment by adagi** [comment]
Oh okay, thank you so much!

**Comment by helloboiss** [comment]
It is detected

**Comment by Plasma2450** [comment]
@helloboiss do you not understand how this works? It's clearly bypassing all possible detection Vectors
