### ISSUE TITLE
probing works, but webradar not

### ISSUE THREAD

**Issue by dbc1998** [EngineOwningSoftware/pcileech-webradar#3]
when starting "pcileech webradar" i get this message

```
[WebRadar by Skyfail] Loading offsets
[WebRadar by Skyfail] Launching HTTP server
[WebRadar by Skyfail] Initializing VMM context
VMM: Skipping process due to parsing error.
     PML4: 0000000000000000 PID: 0 STATE: -2046 EPROCESS: fffff802d7c48128 NAME:

VMM: Skipping process due to parsing error.
     PML4: 0000000000000000 PID: 0 STATE: -2046 EPROCESS: fffff802d7c48128 NAME:

VMM: Skipping process due to parsing error.
     PML4: 0000000000000000 PID: 0 STATE: -2046 EPROCESS: fffff802d7c48128 NAME:

VMM: Skipping process due to parsing error.
     PML4: 0000000000000000 PID: 0 STATE: -2046 EPROCESS: fffff802d7c48128 NAME:

VMM: Skipping process due to parsing error.
     PML4: 0000000000000000 PID: 0 STATE: -2046 EPROCESS: fffff802d7c48128 NAME:

VMM: Skipping process due to parsing error.
     PML4: 0000000000000000 PID: 0 STATE: -2046 EPROCESS: fffff802d7c48128 NAME:
```
is this normal behaviour? its pinging for the process which is not in the ram atm?

after starting csgo it shows and stops

```
[WebRadar by Skyfail] client_panorama.dll: 0x0000000053600000
[WebRadar by Skyfail] engine.dll: 0x000000005FD20000
```

after starting a local game with bots it continues with

```
[WebRadar by Skyfail] Read failed, flushing TLB cache
[WebRadar by Skyfail] Read failed, flushing TLB cache
[WebRadar by Skyfail] client_panorama.dll: 0x0000000053600000
[WebRadar by Skyfail] engine.dll: 0x000000005FD20000
[WebRadar by Skyfail] client_panorama.dll: 0x0000000053600000
[WebRadar by Skyfail] engine.dll: 0x000000005FD20000
```
sometimes it crashes with

`VmmProc: Failed to refresh memory process file system - aborting.`

pcileech probe works tho.  
i have the pciescreamer board with a customized 3.2 build flashed, in device manager it shows the correct spoofed device.

**Comment by tornado240** [comment]
I have the similar issue using the same device, but I have to restart CSGO many times for it to be detected. Once csgo is detected then everything works fine though

**Comment by tornado240** [comment]
This  Skyfail] Read failed, flushing TLB cache happens when you are alt tabbed or changing maps. I know it sounds dumb but make sure your offsets are updated

**Comment by Skyfail** [comment]
Read failed happens when pointers are invalid in csgo, it can be ignored if your offsets are up to date.
The process parsing errors can also be ignored when the game is found.

Please try to download the latest version of this repo, it includes bug fixes by @ufrisk that should fix stability issues with the pciescreamer according to some users.

**Comment by dbc1998** [comment]
Problem is solved now and it seems to run stable.

But so far only with a Default Bios only VT_D Disabled. When using XMP or Overclocking Features im having bsod & detection issues. Ill try to Investigate further today what is causing these issues.

**Comment by Skyfail** [comment]
Good to hear it's working now.
