### ISSUE TITLE
Broken On windows 10 1809

### ISSUE THREAD

**Issue by tornado240** [EngineOwningSoftware/pcileech-webradar#4]
hi, the radar is currently only showing people as soon as the round starts thetn they disappear and every now and then someone will randomly appear on the radar. Im using the latest offsets from hazedumper

**Comment by tornado240** [comment]
Dormant offset needs to manually be updated in the webradar.c

**Comment by helloboiss** [comment]
I encouter the same problem.. changed the value to offsets.GO_Dormant =0xED
What did you exactly changed?

**Comment by Aflic1337** [comment]
How do I fix this? I'm having the same issues all offsets are updated. But sometimes the enemy team will randomly disappear.
