### ISSUE TITLE
plz!

### ISSUE THREAD

**Issue by KirsebaerQAQ** [EngineOwningSoftware/pcileech-webradar#5]
Hello, thank you for creating the project.
If I don't have the compatible hardware you proposed, I only have one PC. How will I use this radar? Thank you.
（I am not very good at English）

**Comment by ramboozer** [comment]
You don't....you need the hardware to use this.....Please read the readme ALL INFORMATION IS HERE...

**Comment by Skyfail** [comment]
A second PC and the hardware is required by design (well, you could run pcileech on the same device but that would defeat the entire purpose of this project).
