### ISSUE TITLE
ESEA/FaceIT

### ISSUE THREAD

**Issue by ghost** [EngineOwningSoftware/pcileech-webradar#6]
-

**Comment by Skyfail** [comment]
No, something else is detected, changing device ids alone will not be sufficient.

**Comment by Euproe** [comment]
Is this still functional today? @Skyfail

**Comment by Skyfail** [comment]
If you update the game specific memory offsets it should still work, however ESEA and FaceIt will detect it.

**Comment by Euproe** [comment]
> If you update the game specific memory offsets it should still work, however ESEA and FaceIt will detect it.

How would you go on about updating something like that? @Skyfail
